//! # Framework Quickstarts
//!
//! Scaffold generators for Next.js, Remix, SvelteKit, FastAPI, Rails, Laravel.
//! Generates a starter project with SDK integration, auth, and data access patterns.

use std::path::Path;
use tracing::info;

#[derive(Debug, Clone)]
pub struct QuickstartTemplate {
    pub framework: String,
    pub files: Vec<TemplateFile>,
    pub install_command: String,
    pub dev_command: String,
}

#[derive(Debug, Clone)]
pub struct TemplateFile {
    pub path: String,
    pub content: String,
}

pub struct QuickstartGenerator;

impl QuickstartGenerator {
    pub fn new() -> Self {
        Self
    }

    pub async fn generate(
        &self,
        framework: &str,
        project_name: &str,
        api_url: &str,
    ) -> Result<Vec<TemplateFile>, String> {
        info!(
            "⚡ Generating {} quickstart for project '{}'",
            framework, project_name
        );

        let template = match framework {
            "nextjs" => Self::nextjs_template(project_name, api_url),
            "remix" => Self::remix_template(project_name, api_url),
            "sveltekit" => Self::sveltekit_template(project_name, api_url),
            "fastapi" => Self::fastapi_template(project_name, api_url),
            _ => return Err(format!("Unknown framework: {}", framework)),
        };

        let mut files = template.files.clone();

        // Add common README
        files.push(TemplateFile {
            path: "README.md".to_string(),
            content: format!(
                r#"# {}

Generated by Stackhouse Quickstart for {}.

## Setup

```bash
{}
```

## Development

```bash
{}
```

## API Configuration

Set your Stackhouse API URL in `.env.local`:
```
NEXT_PUBLIC_STACKHOUSE_URL={}
STACKHOUSE_API_KEY=your_api_key
```

## Features Included

- Authentication (login/signup)
- Data querying and insertion
- Realtime subscriptions (if available)
- Storage uploads
"#,
                project_name, framework, template.install_command, template.dev_command, api_url
            ),
        });

        Ok(files)
    }

    fn nextjs_template(name: &str, api_url: &str) -> QuickstartTemplate {
        QuickstartTemplate {
            framework: "Next.js".to_string(),
            install_command: "npm install @stackhouse/sdk".to_string(),
            dev_command: "npm run dev".to_string(),
            files: vec![
                TemplateFile {
                    path: "package.json".to_string(),
                    content: format!(
                        r#"{{"name":"{}","version":"0.1.0","private":true,"scripts":{{"dev":"next dev","build":"next build","start":"next start"}},"dependencies":{{"next":"^14","react":"^18","react-dom":"^18","@stackhouse/sdk":"^1.0.0"}}}}"#,
                        name
                    ),
                },
                TemplateFile {
                    path: "src/lib/stackhouse.ts".to_string(),
                    content: format!(
                        r#"import {{ StackhouseClient }} from '@stackhouse/sdk';

export const stackhouse = new StackhouseClient({{
    url: process.env.NEXT_PUBLIC_STACKHOUSE_URL || '{}',
    apiKey: process.env.STACKHOUSE_API_KEY,
}});
"#,
                        api_url
                    ),
                },
                TemplateFile {
                    path: "src/app/page.tsx".to_string(),
                    content: r#"'use client';
import { useState, useEffect } from 'react';
import { stackhouse } from '@/lib/stackhouse';

export default function Home() {
    const [data, setData] = useState([]);

    useEffect(() => {
        stackhouse.query('posts').then(setData);
    }, []);

    return (
        <main className="p-8">
            <h1 className="text-2xl font-bold">Stackhouse + Next.js</h1>
            <pre className="bg-gray-100 p-4 mt-4 rounded">{JSON.stringify(data, null, 2)}</pre>
        </main>
    );
}"#
                    .to_string(),
                },
                TemplateFile {
                    path: ".env.local".to_string(),
                    content: format!(
                        "NEXT_PUBLIC_STACKHOUSE_URL={}\nSTACKHOUSE_API_KEY=\n",
                        api_url
                    ),
                },
            ],
        }
    }

    fn remix_template(name: &str, api_url: &str) -> QuickstartTemplate {
        QuickstartTemplate {
            framework: "Remix".to_string(),
            install_command: "npm install @stackhouse/sdk".to_string(),
            dev_command: "npm run dev".to_string(),
            files: vec![
                TemplateFile {
                    path: "package.json".to_string(),
                    content: format!(
                        r#"{{"name":"{}","private":true,"sideEffects":false,"type":"module","scripts":{{"build":"remix build","dev":"remix dev","start":"remix-serve build/index.js"}},"dependencies":{{"@remix-run/node":"^2","@remix-run/react":"^2","@remix-run/serve":"^2","react":"^18","react-dom":"^18","@stackhouse/sdk":"^1.0.0"}}}}"#,
                        name
                    ),
                },
                TemplateFile {
                    path: "app/lib/stackhouse.server.ts".to_string(),
                    content: format!(
                        r#"import {{ StackhouseClient }} from '@stackhouse/sdk';

export const stackhouse = new StackhouseClient({{
    url: process.env.STACKHOUSE_URL || '{}',
    apiKey: process.env.STACKHOUSE_API_KEY,
}});
"#,
                        api_url
                    ),
                },
                TemplateFile {
                    path: "app/routes/_index.tsx".to_string(),
                    content: r#"import { json } from '@remix-run/node';
import { useLoaderData } from '@remix-run/react';
import { stackhouse } from '~/lib/stackhouse.server';

export const loader = async () => {
    const data = await stackhouse.query('posts');
    return json({ data });
};

export default function Index() {
    const { data } = useLoaderData<typeof loader>();
    return (
        <div className="p-8">
            <h1 className="text-2xl font-bold">Stackhouse + Remix</h1>
            <pre className="bg-gray-100 p-4 mt-4 rounded">{JSON.stringify(data, null, 2)}</pre>
        </div>
    );
}"#
                    .to_string(),
                },
            ],
        }
    }

    fn sveltekit_template(name: &str, api_url: &str) -> QuickstartTemplate {
        QuickstartTemplate {
            framework: "SvelteKit".to_string(),
            install_command: "npm install @stackhouse/sdk".to_string(),
            dev_command: "npm run dev".to_string(),
            files: vec![
                TemplateFile {
                    path: "package.json".to_string(),
                    content: format!(
                        r#"{{"name":"{}","version":"0.0.1","private":true,"scripts":{{"dev":"vite dev","build":"vite build","preview":"vite preview"}},"devDependencies":{{"@sveltejs/adapter-auto":"^3","@sveltejs/kit":"^2","svelte":"^4","vite":"^5","typescript":"^5"}},"dependencies":{{"@stackhouse/sdk":"^1.0.0"}}}}"#,
                        name
                    ),
                },
                TemplateFile {
                    path: "src/lib/stackhouse.ts".to_string(),
                    content: format!(
                        r#"import {{ StackhouseClient }} from '@stackhouse/sdk';

export const stackhouse = new StackhouseClient({{
    url: import.meta.env.VITE_STACKHOUSE_URL || '{}',
    apiKey: import.meta.env.VITE_STACKHOUSE_API_KEY,
}});
"#,
                        api_url
                    ),
                },
                TemplateFile {
                    path: "src/routes/+page.svelte".to_string(),
                    content: r#"<script>
    import { stackhouse } from '$lib/stackhouse';
    import { onMount } from 'svelte';

    let data = [];
    onMount(async () => {
        data = await stackhouse.query('posts');
    });
</script>

<div class="p-8">
    <h1 class="text-2xl font-bold">Stackhouse + SvelteKit</h1>
    <pre class="bg-gray-100 p-4 mt-4 rounded">{JSON.stringify(data, null, 2)}</pre>
</div>"#
                        .to_string(),
                },
            ],
        }
    }

    fn fastapi_template(_name: &str, api_url: &str) -> QuickstartTemplate {
        QuickstartTemplate {
            framework: "FastAPI".to_string(),
            install_command: "pip install stackhouse-sdk fastapi uvicorn".to_string(),
            dev_command: "uvicorn main:app --reload".to_string(),
            files: vec![
                TemplateFile {
                    path: "requirements.txt".to_string(),
                    content: "fastapi\nuvicorn\nstackhouse-sdk>=1.0.0\n".to_string(),
                },
                TemplateFile {
                    path: "main.py".to_string(),
                    content: format!(
                        r#"from fastapi import FastAPI
from stackhouse import StackhouseClient
import os

app = FastAPI()
stackhouse = StackhouseClient(
    url=os.getenv("STACKHOUSE_URL", "{}"),
    api_key=os.getenv("STACKHOUSE_API_KEY")
)

@app.get("/")
async def root():
    data = await stackhouse.query("posts")
    return {{"data": data}}

@app.post("/posts")
async def create_post(post: dict):
    result = await stackhouse.push("posts", post)
    return result
"#,
                        api_url
                    ),
                },
                TemplateFile {
                    path: ".env".to_string(),
                    content: format!("STACKHOUSE_URL={}\nSTACKHOUSE_API_KEY=\n", api_url),
                },
            ],
        }
    }

    /// Write generated files to disk
    pub async fn write_files<P: AsRef<Path>>(
        &self,
        base_dir: P,
        files: &[TemplateFile],
    ) -> Result<(), String> {
        for file in files {
            let full_path = base_dir.as_ref().join(&file.path);
            if let Some(parent) = full_path.parent() {
                tokio::fs::create_dir_all(parent)
                    .await
                    .map_err(|e| format!("Create dir: {}", e))?;
            }
            tokio::fs::write(&full_path, &file.content)
                .await
                .map_err(|e| format!("Write file: {}", e))?;
        }
        Ok(())
    }
}
