//! # Auto-Generated TypeScript Types from Postgres Schema
//!
//! Generates TypeScript interfaces from database tables, enums,
//! and composite types for type-safe SDK usage.

use crate::db::StackhouseStore;
use crate::error::{StackhouseError, StackhouseResult};

use std::sync::Arc;
use tracing::info;

#[derive(Clone)]
pub struct TypeScriptGenerator {
    store: Arc<StackhouseStore>,
}

impl TypeScriptGenerator {
    pub fn new(store: Arc<StackhouseStore>) -> Self {
        Self { store }
    }

    /// Generate TypeScript types for all tables
    pub async fn generate(&self) -> StackhouseResult<String> {
        let mut output = String::new();
        output.push_str("// Auto-generated by Stackhouse TypeScript Generator\n\n");

        // Get all tables
        let tables = self.store.query(
            "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE' AND table_name LIKE 'stackhouse_%' ORDER BY table_name".to_string(),
            vec![],
        ).await?;

        for row in &tables {
            let table_name = row
                .iter()
                .find(|(k, _)| k == "table_name")
                .and_then(|(_, v)| v.as_str())
                .unwrap_or("");
            if let Ok(ts) = self.generate_table_type(table_name).await {
                output.push_str(&ts);
                output.push('\n');
            }
        }

        // Generate common types
        output.push_str(&self.generate_common_types());

        info!("📝 Generated TypeScript types for {} tables", tables.len());
        Ok(output)
    }

    async fn generate_table_type(&self, table_name: &str) -> StackhouseResult<String> {
        let columns = self.store.query(
            format!("SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns WHERE table_name = '{}' ORDER BY ordinal_position", table_name),
            vec![],
        ).await?;

        let interface_name = Self::to_pascal_case(table_name.trim_start_matches("stackhouse_"));
        let mut lines = vec![format!("export interface {} {{", interface_name)];

        for col in &columns {
            let name = col
                .iter()
                .find(|(k, _)| k == "column_name")
                .and_then(|(_, v)| v.as_str())
                .unwrap_or("");
            let data_type = col
                .iter()
                .find(|(k, _)| k == "data_type")
                .and_then(|(_, v)| v.as_str())
                .unwrap_or("text");
            let nullable = col
                .iter()
                .find(|(k, _)| k == "is_nullable")
                .and_then(|(_, v)| v.as_str())
                == Some("YES");
            let ts_type = Self::postgres_to_ts(data_type);

            let optional = if nullable { "?" } else { "" };
            lines.push(format!("  {}{}: {};", name, optional, ts_type));
        }

        lines.push("}\n".to_string());

        // Generate insert type (all optional)
        lines.push(format!("export interface {}Insert {{", interface_name));
        for col in &columns {
            let name = col
                .iter()
                .find(|(k, _)| k == "column_name")
                .and_then(|(_, v)| v.as_str())
                .unwrap_or("");
            let data_type = col
                .iter()
                .find(|(k, _)| k == "data_type")
                .and_then(|(_, v)| v.as_str())
                .unwrap_or("text");
            let ts_type = Self::postgres_to_ts(data_type);
            lines.push(format!("  {}?: {};", name, ts_type));
        }
        lines.push("}\n".to_string());

        Ok(lines.join("\n"))
    }

    fn generate_common_types(&self) -> String {
        r#"
export interface StackhouseResponse<T> {
  success: boolean;
  data: T;
  error?: string;
}

export interface QueryOptions {
  filter?: Record<string, unknown>;
  sort?: string;
  limit?: number;
  offset?: number;
  select?: string;
}

export interface AuthTokens {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  token_type: string;
}

export interface User {
  id: number;
  email: string;
  created_at: string;
  updated_at: string;
  metadata?: Record<string, unknown>;
}

export type LogLevel = 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';

export interface LogEntry {
  service: string;
  level: LogLevel;
  message: string;
  timestamp: string;
  trace_id?: string;
}
"#
        .to_string()
    }

    fn postgres_to_ts(pg_type: &str) -> String {
        match pg_type {
            "integer" | "bigint" | "smallint" | "serial" | "bigserial" => "number".into(),
            "numeric" | "decimal" | "real" | "double precision" => "number".into(),
            "text" | "varchar" | "char" | "character varying" | "uuid" => "string".into(),
            "boolean" => "boolean".into(),
            "timestamp" | "timestamp with time zone" | "date" | "time" => "string".into(),
            "json" | "jsonb" => "Record<string, unknown>".into(),
            "bytea" => "Uint8Array".into(),
            "ARRAY" => "unknown[]".into(),
            _ => "unknown".into(),
        }
    }

    fn to_pascal_case(s: &str) -> String {
        s.split('_')
            .map(|w| {
                let mut chars = w.chars();
                match chars.next() {
                    Some(c) => {
                        c.to_uppercase().collect::<String>() + &chars.as_str().to_lowercase()
                    }
                    None => String::new(),
                }
            })
            .collect()
    }

    /// Write types to a file
    pub async fn write_to_file<P: AsRef<std::path::Path>>(&self, path: P) -> StackhouseResult<()> {
        let types = self.generate().await?;
        tokio::fs::write(path, types)
            .await
            .map_err(|e| StackhouseError::Internal(anyhow::anyhow!("Write types: {}", e)))?;
        Ok(())
    }
}
