{{- if .Values.stackhouse.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stackhouse.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackhouse.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.stackhouse.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .Values.stackhouse.persistence.storageClass }}
  storageClassName: {{ .Values.stackhouse.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.stackhouse.persistence.size }}
{{- end }}
